using System.Collections.Generic;
using Gameplay.Particles;

namespace Gameplay.Objects
{
	public class ObjectParticleMaps
	{
		public static readonly Dictionary<(ObjectType type, int volume), ParticleType> TntExplodeParticles = new Dictionary<(ObjectType type, int volume), ParticleType>
		{
			[(ObjectType.StoneSquare, 1)] = ParticleType.Stone1xTntExplode,
			[(ObjectType.StoneSquare, 2)] = ParticleType.Stone2xTntExplode,
			[(ObjectType.StoneSquare, 3)] = ParticleType.Stone3xTntExplode,
			[(ObjectType.StoneSquare, 4)] = ParticleType.Stone4xTntExplode,
			[(ObjectType.StoneSquare, 5)] = ParticleType.Stone5xTntExplode,
			[(ObjectType.StoneCylinder, 1)] = ParticleType.StoneCylinder1xTntExplode,
			[(ObjectType.StoneCylinder, 2)] = ParticleType.StoneCylinder2xTntExplode,
			[(ObjectType.StoneCylinder, 3)] = ParticleType.StoneCylinder3xTntExplode,
			[(ObjectType.StoneCylinder, 4)] = ParticleType.StoneCylinder4xTntExplode,
			[(ObjectType.StoneCylinder, 5)] = ParticleType.StoneCylinder5xTntExplode,
			[(ObjectType.CanCylinder, 1)] = ParticleType.CanCylinder1xTntExplode,
			[(ObjectType.CanCylinder, 2)] = ParticleType.CanCylinder2xTntExplode,
			[(ObjectType.CanCylinder, 3)] = ParticleType.CanCylinder3xTntExplode,
			[(ObjectType.CanCylinder, 4)] = ParticleType.CanCylinder4xTntExplode,
			[(ObjectType.CanCylinder, 5)] = ParticleType.CanCylinder5xTntExplode,
			[(ObjectType.CanSquare, 1)] = ParticleType.CanSquare1xTntExplode,
			[(ObjectType.CanSquare, 2)] = ParticleType.CanSquare2xTntExplode,
			[(ObjectType.CanSquare, 3)] = ParticleType.CanSquare3xTntExplode,
			[(ObjectType.CanSquare, 4)] = ParticleType.CanSquare4xTntExplode,
			[(ObjectType.CanSquare, 5)] = ParticleType.CanSquare5xTntExplode,
			[(ObjectType.CanCone, 0)] = ParticleType.CanConeTntExplode,
			[(ObjectType.BoxSquare, 1)] = ParticleType.BoxBreak1xTntExplode,
			[(ObjectType.BoxSquare, 2)] = ParticleType.BoxBreak2xTntExplode,
			[(ObjectType.BoxSquare, 3)] = ParticleType.BoxBreak3xTntExplode,
			[(ObjectType.BoxSquare, 4)] = ParticleType.BoxBreak4xTntExplode,
			[(ObjectType.BoxSquare, 5)] = ParticleType.BoxBreak5xTntExplode,
			[(ObjectType.BoxCylinder, 1)] = ParticleType.BoxCylinderBreak1xTntExplode,
			[(ObjectType.BoxCylinder, 2)] = ParticleType.BoxCylinderBreak2xTntExplode,
			[(ObjectType.BoxCylinder, 3)] = ParticleType.BoxCylinderBreak3xTntExplode,
			[(ObjectType.BoxCylinder, 4)] = ParticleType.BoxCylinderBreak4xTntExplode,
			[(ObjectType.BoxCylinder, 5)] = ParticleType.BoxCylinderBreak5xTntExplode,
			[(ObjectType.IceSquare, 1)] = ParticleType.Ice1xTntExplode,
			[(ObjectType.IceSquare, 2)] = ParticleType.Ice2xTntExplode,
			[(ObjectType.IceSquare, 3)] = ParticleType.Ice3xTntExplode,
			[(ObjectType.IceSquare, 4)] = ParticleType.Ice4xTntExplode,
			[(ObjectType.IceSquare, 5)] = ParticleType.Ice5xTntExplode,
			[(ObjectType.IceSquare, 6)] = ParticleType.Ice6xTntExplode,
			[(ObjectType.IceSquare, 7)] = ParticleType.Ice7xTntExplode,
			[(ObjectType.IceSquare, 8)] = ParticleType.Ice8xTntExplode,
			[(ObjectType.IceCylinder, 1)] = ParticleType.IceCylinder1xTntExplode,
			[(ObjectType.IceCylinder, 2)] = ParticleType.IceCylinder2xTntExplode,
			[(ObjectType.IceCylinder, 3)] = ParticleType.IceCylinder3xTntExplode,
			[(ObjectType.IceCylinder, 4)] = ParticleType.IceCylinder4xTntExplode,
			[(ObjectType.IceCylinder, 5)] = ParticleType.IceCylinder5xTntExplode
		};

		public static readonly Dictionary<(ObjectType type, int volume), ParticleType> PlayParticles = new Dictionary<(ObjectType type, int volume), ParticleType>
		{
			[(ObjectType.StoneSquare, 1)] = ParticleType.StoneCube1x,
			[(ObjectType.StoneSquare, 2)] = ParticleType.StoneCube2x,
			[(ObjectType.StoneSquare, 3)] = ParticleType.StoneCube3x,
			[(ObjectType.StoneSquare, 4)] = ParticleType.StoneCube4x,
			[(ObjectType.StoneSquare, 5)] = ParticleType.StoneCube5x,
			[(ObjectType.StoneCylinder, 1)] = ParticleType.StoneCylinder1x,
			[(ObjectType.StoneCylinder, 2)] = ParticleType.StoneCylinder2x,
			[(ObjectType.StoneCylinder, 3)] = ParticleType.StoneCylinder3x,
			[(ObjectType.StoneCylinder, 4)] = ParticleType.StoneCylinder4x,
			[(ObjectType.StoneCylinder, 5)] = ParticleType.StoneCylinder5x,
			[(ObjectType.CanCylinder, 1)] = ParticleType.CanCylinder1x,
			[(ObjectType.CanCylinder, 2)] = ParticleType.CanCylinder2x,
			[(ObjectType.CanCylinder, 3)] = ParticleType.CanCylinder3x,
			[(ObjectType.CanCylinder, 4)] = ParticleType.CanCylinder4x,
			[(ObjectType.CanCylinder, 5)] = ParticleType.CanCylinder5x,
			[(ObjectType.CanSquare, 1)] = ParticleType.CanSquare1x,
			[(ObjectType.CanSquare, 2)] = ParticleType.CanSquare2x,
			[(ObjectType.CanSquare, 3)] = ParticleType.CanSquare3x,
			[(ObjectType.CanSquare, 4)] = ParticleType.CanSquare4x,
			[(ObjectType.CanSquare, 5)] = ParticleType.CanSquare5x,
			[(ObjectType.CanCone, 0)] = ParticleType.CanCone,
			[(ObjectType.BoxSquare, 1)] = ParticleType.BoxBreak1x,
			[(ObjectType.BoxSquare, 2)] = ParticleType.BoxBreak2x,
			[(ObjectType.BoxSquare, 3)] = ParticleType.BoxBreak3x,
			[(ObjectType.BoxSquare, 4)] = ParticleType.BoxBreak4x,
			[(ObjectType.BoxSquare, 5)] = ParticleType.BoxBreak5x,
			[(ObjectType.BoxCylinder, 1)] = ParticleType.BoxCylinderBreak1x,
			[(ObjectType.BoxCylinder, 2)] = ParticleType.BoxCylinderBreak2x,
			[(ObjectType.BoxCylinder, 3)] = ParticleType.BoxCylinderBreak3x,
			[(ObjectType.BoxCylinder, 4)] = ParticleType.BoxCylinderBreak4x,
			[(ObjectType.BoxCylinder, 5)] = ParticleType.BoxCylinderBreak5x,
			[(ObjectType.IceSquare, 1)] = ParticleType.Ice1xGround,
			[(ObjectType.IceSquare, 2)] = ParticleType.Ice2xGround,
			[(ObjectType.IceSquare, 3)] = ParticleType.Ice3xGround,
			[(ObjectType.IceSquare, 4)] = ParticleType.Ice4xGround,
			[(ObjectType.IceSquare, 5)] = ParticleType.Ice5xGround,
			[(ObjectType.IceSquare, 6)] = ParticleType.Ice6xGround,
			[(ObjectType.IceSquare, 7)] = ParticleType.Ice7xGround,
			[(ObjectType.IceSquare, 8)] = ParticleType.Ice8xGround,
			[(ObjectType.IceCylinder, 1)] = ParticleType.IceCylinder1xGround,
			[(ObjectType.IceCylinder, 2)] = ParticleType.IceCylinder2xGround,
			[(ObjectType.IceCylinder, 3)] = ParticleType.IceCylinder3xGround,
			[(ObjectType.IceCylinder, 4)] = ParticleType.IceCylinder4xGround,
			[(ObjectType.IceCylinder, 5)] = ParticleType.IceCylinder5xGround
		};
	}
}
